//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HttpServer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpServerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpServerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HttpServer.HttpServerResources", typeof(HttpServerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud del procesador por defecto.
        /// </summary>
        internal static string DefaultProcessRequestStatus {
            get {
                return ResourceManager.GetString("DefaultProcessRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta del procesador por defecto.
        /// </summary>
        internal static string DefaultProcessResponseStatus {
            get {
                return ResourceManager.GetString("DefaultProcessResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type.
        /// </summary>
        internal static string HeaderContentType {
            get {
                return ResourceManager.GetString("HeaderContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string HeaderContentTypeHtml {
            get {
                return ResourceManager.GetString("HeaderContentTypeHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-ddTHH\\:mm\\:ss.fffffff.
        /// </summary>
        internal static string HeaderGeneralDateFormat {
            get {
                return ResourceManager.GetString("HeaderGeneralDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string HeaderGeneralDateName {
            get {
                return ResourceManager.GetString("HeaderGeneralDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string HeaderGeneralServerName {
            get {
                return ResourceManager.GetString("HeaderGeneralServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h1&gt;.
        /// </summary>
        internal static string HtmlH1 {
            get {
                return ResourceManager.GetString("HtmlH1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/h1&gt;.
        /// </summary>
        internal static string HtmlH1Closed {
            get {
                return ResourceManager.GetString("HtmlH1Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.
        /// </summary>
        internal static string HttpVersion {
            get {
                return ResourceManager.GetString("HttpVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./RequestLog.txt.
        /// </summary>
        internal static string LoggerFileName {
            get {
                return ResourceManager.GetString("LoggerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud en el logger.
        /// </summary>
        internal static string LoggerProcessRequestStatus {
            get {
                return ResourceManager.GetString("LoggerProcessRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta en el logger.
        /// </summary>
        internal static string LoggerProcessResponseStatus {
            get {
                return ResourceManager.GetString("LoggerProcessResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión cerrada.
        /// </summary>
        internal static string ServerStatusMessageClose {
            get {
                return ResourceManager.GetString("ServerStatusMessageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------.
        /// </summary>
        internal static string ServerStatusMessageLines {
            get {
                return ResourceManager.GetString("ServerStatusMessageLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conexión recibida.
        /// </summary>
        internal static string ServerStatusMessageRecibe {
            get {
                return ResourceManager.GetString("ServerStatusMessageRecibe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eperando conexiones.......
        /// </summary>
        internal static string ServerStatusMessageWait {
            get {
                return ResourceManager.GetString("ServerStatusMessageWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string StatusCode200 {
            get {
                return ResourceManager.GetString("StatusCode200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string StatusCode200Message {
            get {
                return ResourceManager.GetString("StatusCode200Message", resourceCulture);
            }
        }
    }
}
